# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\github\League-of-Legends\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QCoreApplication
from PyQt5.QtWidgets import QWidget, QLCDNumber, QSlider, QVBoxLayout, QApplication, QPushButton, QTabWidget
from PyQt5.QtGui import QIcon


class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(741, 517)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\github\\League-of-Legends\\favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TabWidget.setWindowIcon(icon)
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(360, 190, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        TabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(450, 390, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(580, 390, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        TabWidget.addTab(self.tab, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(1)
        self.pushButton_3.clicked.connect(TabWidget.close)
        self.pushButton_2.clicked.connect(TabWidget.close)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "Test"))
        self.pushButton_3.setText(_translate("TabWidget", "退出"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_2), _translate("TabWidget", "Tab 1"))
        self.pushButton.setText(_translate("TabWidget", "ok"))
        self.pushButton_2.setText(_translate("TabWidget", "cancel"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), _translate("TabWidget", "Tab 2"))

if __name__ == "__main__":
    app = QApplication(sys.argv)
    form = QTabWidget()
    fscldd = Ui_TabWidget()
    fscldd.setupUi(form)
    form.show()
    sys.exit(app.exec_())
